# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64848298a0775a352c8377bb244369bdce8b4fa064aee7c0363ca94d5c7065b81a06a84c80d9f8d2cf3f7545c63d3f22dc9e91ae9337ff206bbcb2652cb56fe9

test:
  secret_key_base: 0e0fb813a4d624fb4bd55c9ec58619a4a531bc6ec9cc551586b41aa77a4184dad650dd4bbffabbd1bcf7fa40d2244d1bdd93ae68eccd068ac357587d604d7c37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
